#!/usr/bin/env node

const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '.env.local' });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing Supabase credentials in .env.local');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const passages = [
  // The Stoics Path - 25 substantial passages from Marcus Aurelius, Seneca, and Epictetus
  { path: 'stoics', title: 'Power Over Mind', author: 'Marcus Aurelius', content: 'You have power over your mind—not outside events. Realize this, and you will find strength in the understanding that external circumstances cannot disturb your inner peace.', difficulty_order: 1 },
  { path: 'stoics', title: 'What We Control', author: 'Epictetus', content: 'Some things are in our control and others not. Things in our control are opinion, pursuit, desire, aversion, and in a word, whatever are our own actions.', difficulty_order: 2 },
  { path: 'stoics', title: 'Time as River', author: 'Marcus Aurelius', content: 'Time is like a river of passing events and the current is swift. No sooner does anything appear than it has swept by, and another comes in its place.', difficulty_order: 3 },
  { path: 'stoics', title: 'True Wealth', author: 'Seneca', content: 'Every new beginning comes from some other beginning\'s end. It is not the man who has too little, but the man who craves more, who is poor.', difficulty_order: 4 },
  { path: 'stoics', title: 'Universal Reason', author: 'Marcus Aurelius', content: 'Constantly regard the universe as one living being, having one substance and one soul. All things are mutually woven together and the bond is sacred; there is hardly anything unconnected.', difficulty_order: 5 },
  { path: 'stoics', title: 'Philosophy as Practice', author: 'Epictetus', content: 'Don\'t explain your philosophy. Embody it. The greater the difficulty, the greater the glory in surmounting it. Skillful pilots gain their reputation from storms and tempests rather than from calm seas.', difficulty_order: 6 },
  { path: 'stoics', title: 'Anger as Madness', author: 'Seneca', content: 'Anger, if not restrained, is frequently more hurtful to us than the injury that provokes it. No one can have all he wants, but a man can refrain from wanting what he has not.', difficulty_order: 7 },
  { path: 'stoics', title: 'Morning Preparation', author: 'Marcus Aurelius', content: 'When you wake up in the morning, tell yourself: The people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous, and surly. They are like this because they can\'t tell good from evil.', difficulty_order: 8 },
  { path: 'stoics', title: 'The Inner Citadel', author: 'Epictetus', content: 'He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has. When someone is properly grounded in life, they shouldn\'t have to look outside themselves for approval.', difficulty_order: 9 },
  { path: 'stoics', title: 'Virtue as the Only Good', author: 'Marcus Aurelius', content: 'Very little is needed to make a happy life; it is all within yourself, in your way of thinking. How much trouble he avoids who does not look to see what his neighbor says or does, but only to what he does himself.', difficulty_order: 10 },
  { path: 'stoics', title: 'On Wealth and Poverty', author: 'Seneca', content: 'It is not the man who has too little, but the man who craves more, who is poor. What does it matter how much you have laid up, if you think of what is still lacking? Conversely, what does it matter how little you have, if you do not yearn for more?', difficulty_order: 11 },
  { path: 'stoics', title: 'The Discipline of Desire', author: 'Epictetus', content: 'Remember that you must behave in life as you would behave at a banquet. Is anything brought around to you? Put out your hand and take your share with moderation. Does it pass by you? Do not stop it. Is it not yet come? Do not stretch your desire towards it, but wait.', difficulty_order: 12 },
  { path: 'stoics', title: 'Death as Teacher', author: 'Marcus Aurelius', content: 'It is not death that a man should fear, but never beginning to live. Death smiles at us all, but all a man can do is smile back. The act of dying is one of the acts of life. Consider that everything is opinion. How much trouble he avoids who does not look to see what his neighbor says.', difficulty_order: 13 },
  { path: 'stoics', title: 'Preparing for Adversity', author: 'Seneca', content: 'What is grief but an opinion? Set aside a certain number of days, during which you shall be content with the scantiest and cheapest fare, with coarse and rough dress, saying to yourself the while: "Is this the condition that I feared?" It is likely that some troubles will befall us; but it is not a present fact. How often has the unexpected happened! How often has the expected never come to pass!', difficulty_order: 14 },
  { path: 'stoics', title: 'The View from Above', author: 'Marcus Aurelius', content: 'Remember how brief life is, how vast the universe. What we do now echoes in eternity. Constantly regard the universe as one living being, having one substance and one soul. All things are mutually woven together and the bond is sacred; there is hardly anything unconnected with any other thing. For we were born to work together like feet, hands, and eyes, like the two rows of teeth, upper and lower. To obstruct each other is unnatural.', difficulty_order: 15 },
  { path: 'stoics', title: 'On True Freedom', author: 'Epictetus', content: 'No one can harm you without your permission. The person who betrays you is not your enemy—your uncontrolled reactions are. You are an actor in a play, which is as the author wants it to be; if short, then short; if long, then long; if he wants you to play a poor man, play even that role skillfully; and similarly if a cripple, or a public official, or a private citizen. For this is your business, to play admirably the role assigned you; but the selection of that role is Another\'s.', difficulty_order: 16 },
  { path: 'stoics', title: 'The Shortness of Life', author: 'Seneca', content: 'Life is long enough if you know how to use it. But when it is wasted in heedless luxury and spent on no good activity, we are forced at last by death\'s final constraint to realize that it has passed away before we knew it was passing. So it is: we receive not a short life but we make it short, and we are not ill-provided but wasteful of it. Just as when ample and princely wealth falls to a bad owner it is squandered in a moment, but wealth however small, if entrusted to a good custodian, increases with use, so our lifetime extends widely if you manage it properly.', difficulty_order: 17 },
  { path: 'stoics', title: 'The Unity of All Things', author: 'Marcus Aurelius', content: 'We were born to work together like feet, hands, and eyes, like the two rows of teeth, upper and lower. To obstruct each other is unnatural. To feel anger at someone, to turn your back on him: these are obstructions. Constantly regard the universe as one living being, having one substance and one soul; and observe how all things have reference to one perception, the perception of this one living being; and how all things act with one movement; and how all things are the cooperating causes of all things which exist; observe too the continuous spinning of the thread and the contexture of the web.', difficulty_order: 18 },
  { path: 'stoics', title: 'On Virtue and Character', author: 'Seneca', content: 'Every new beginning comes from some other beginning\'s end. What is quite unlooked for is more crushing in its effect, and unexpectedness adds to the weight of a disaster. A long-expected blow falls more gently. Therefore, let not your mind be crushed beneath the sudden impulse of circumstances. Long before the first day of our lives, we had our fates assigned to us; and each of us will meet the end which was spun for him from the beginning. Some things, it is true, the wise man does not fear even though they inspire fear in others, and some things he fears even though others are not afraid. The former attitude is that of one whose reason is sound, the latter of one who errs. The wise man will be prepared for either fortune.', difficulty_order: 19 },
  { path: 'stoics', title: 'The Philosopher\'s Discipline', author: 'Epictetus', content: 'When you wake up in the morning, tell yourself: The people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous, and surly. They are like this because they can\'t tell good from evil. But I have seen the beauty of good, and the ugliness of evil, and have recognized that the wrongdoer has a nature related to my own—not of the same blood or birth, but the same mind, and possessing a share of the divine. And so none of them can hurt me. No one can implicate me in ugliness, nor can I feel angry at my relative, or hate him. We were born to work together like feet, hands, and eyes, like the two rows of teeth, upper and lower. To obstruct each other is unnatural. Constantly regard the universe as one living being, having one substance and one soul.', difficulty_order: 20 },
  { path: 'stoics', title: 'On Fortune and Providence', author: 'Seneca', content: 'Fortune is glass: just when it is brightest it is shattered. No one can be said to be happy who has been thrust outside the pale of truth. And it is clear that nothing, to a mind reasoning soundly, is really bad but the absence of good. We were born to work together like feet, hands, and eyes, like the two rows of teeth, upper and lower. Every new beginning comes from some other beginning\'s end. Life is long enough if you know how to use it. But when it is wasted in heedless luxury and spent on no good activity, we are forced at last by death\'s final constraint to realize that it has passed away before we knew it was passing. Nothing, to my way of thinking, is a better proof of a well-ordered mind than a man\'s ability to stop just where he is and pass some time in his own company.', difficulty_order: 21 },
  { path: 'stoics', title: 'The Cosmic City', author: 'Marcus Aurelius', content: 'Constantly regard the universe as one living being, having one substance and one soul; and observe how all things have reference to one perception, the perception of this one living being; and how all things act with one movement; and how all things are the cooperating causes of all things which exist; observe too the continuous spinning of the thread and the contexture of the web. We were born to work together like feet, hands, and eyes, like the two rows of teeth, upper and lower. To obstruct each other is unnatural. To feel anger at someone, to turn your back on him: these are obstructions. As you take your morning walk, meditate thus: I go to meet today insolence, ingratitude, treachery, malice, selfishness. They are the fruits of ignorance and error. As for me, I have long perceived the nature of good and its nobility, the nature of evil and its meanness, the nature even of the culprit himself, who is my brother, partaking of the same reason and the same portion of the divine.', difficulty_order: 22 },
  { path: 'stoics', title: 'The Practice of Philosophy', author: 'Epictetus', content: 'Don\'t explain your philosophy. Embody it. When you do anything from a clear judgment that it ought to be done, never shrink from being seen to do it, even though the world should make a wrong supposition about it; for, if you don\'t act right, shun the action itself; but, if you do, why are you afraid of those who censure you wrongly? The key is to keep company only with people who uplift you, whose presence calls forth your best. But remember that you must behave in life as you would behave at a banquet. Is anything brought around to you? Put out your hand and take your share with moderation. Does it pass by you? Do not stop it. Is it not yet come? Do not stretch your desire towards it, but wait until it reaches you. So with regard to children, so with regard to a wife, so with regard to office, so with regard to wealth, and you will sometime be worthy of the banquets of the gods. And if you do not so much as take the things which are set before you, but are able even to reject them, then you will not only be worthy of the banquets of the gods, but of rule with them also.', difficulty_order: 23 },
  { path: 'stoics', title: 'On Wisdom and Virtue', author: 'Marcus Aurelius', content: 'Remember how brief life is, how vast the universe. What we do now echoes in eternity. How much trouble he avoids who does not look to see what his neighbor says or does, but only to what he does himself. The universe is transformation; our life is what our thoughts make it. Very little is needed to make a happy life; it is all within yourself, in your way of thinking. Constantly regard the universe as one living being, having one substance and one soul. All things are mutually woven together and the bond is sacred; there is hardly anything unconnected with any other thing. For we were born to work together like feet, hands, and eyes, like the two rows of teeth, upper and lower. To obstruct each other is unnatural. To feel anger at someone, to turn your back on him: these are obstructions. You have power over your mind—not outside events. Realize this, and you will find strength. When you wake up in the morning, tell yourself: The people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous, and surly. They are like this because they can\'t tell good from evil. But I have seen the beauty of good, and the ugliness of evil, and have recognized that the wrongdoer has a nature related to my own.', difficulty_order: 24 },
  { path: 'stoics', title: 'The Complete Stoic Life', author: 'Seneca', content: 'Every new beginning comes from some other beginning\'s end. What is quite unlooked for is more crushing in its effect, and unexpectedness adds to the weight of a disaster. A long-expected blow falls more gently. Therefore, let not your mind be crushed beneath the sudden impulse of circumstances. Long before the first day of our lives, we had our fates assigned to us; and each of us will meet the end which was spun for him from the beginning. Some things, it is true, the wise man does not fear even though they inspire fear in others, and some things he fears even though others are not afraid. The former attitude is that of one whose reason is sound, the latter of one who errs. The wise man will be prepared for either fortune. Nothing, to my way of thinking, is a better proof of a well-ordered mind than a man\'s ability to stop just where he is and pass some time in his own company. Be always like this, that when Death comes to fetch you, you may be found ready to depart, and need ask delay from none. You will thus practice dying. What is grief but an opinion? Set aside a certain number of days, during which you shall be content with the scantiest and cheapest fare, with coarse and rough dress, saying to yourself the while: "Is this the condition that I feared?" It is likely that some troubles will befall us; but it is not a present fact.', difficulty_order: 25 },

  // The Founders Path - 20 passages from American founding documents and speeches
  { path: 'founders', title: 'Self-Evident Truths', author: 'Declaration of Independence', content: 'We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights.', difficulty_order: 1 },
  { path: 'founders', title: 'Consent of the Governed', author: 'Declaration of Independence', content: 'Governments are instituted among Men, deriving their just powers from the consent of the governed.', difficulty_order: 2 },
  { path: 'founders', title: 'Constitutional Preamble', author: 'U.S. Constitution', content: 'We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defence.', difficulty_order: 3 },
  { path: 'founders', title: 'Life, Liberty, and Happiness', author: 'Declaration of Independence', content: 'That among these are Life, Liberty and the pursuit of Happiness. That to secure these rights, Governments are instituted among Men.', difficulty_order: 4 },
  { path: 'founders', title: 'Four Score and Seven Years', author: 'Abraham Lincoln', content: 'Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.', difficulty_order: 5 },
  { path: 'founders', title: 'Foreign Entanglements', author: 'George Washington', content: 'It is our true policy to steer clear of permanent alliances with any portion of the foreign world; so far, I mean, as we are now at liberty to do it.', difficulty_order: 6 },
  { path: 'founders', title: 'The Tree of Liberty', author: 'Thomas Jefferson', content: 'The tree of liberty must be refreshed from time to time with the blood of patriots and tyrants. It is its natural manure.', difficulty_order: 7 },
  { path: 'founders', title: 'Ambition Countering Ambition', author: 'James Madison', content: 'Ambition must be made to counteract ambition. The interest of the man must be connected with the constitutional rights of the place.', difficulty_order: 8 },
  { path: 'founders', title: 'Honest Abe on Honesty', author: 'Abraham Lincoln', content: 'Stand with anybody who stands right. Stand with him while he is right and part with him when he goes wrong.', difficulty_order: 9 },
  { path: 'founders', title: 'Early to Bed', author: 'Benjamin Franklin', content: 'Early to bed and early to rise, makes a man healthy, wealthy and wise. An investment in knowledge pays the best interest.', difficulty_order: 10 },
  { path: 'founders', title: 'Securing Liberty\'s Blessings', author: 'U.S. Constitution', content: 'We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defence, promote the general Welfare, and secure the Blessings of Liberty to ourselves and our Posterity, do ordain and establish this Constitution for the United States of America.', difficulty_order: 11 },
  { path: 'founders', title: 'Taxation Without Representation', author: 'Declaration of Independence', content: 'For imposing Taxes on us without our Consent: For depriving us in many cases, of the benefits of Trial by Jury: For transporting us beyond Seas to be tried for pretended offences: For abolishing the free System of English Laws in a neighbouring Province, establishing therein an Arbitrary government, and enlarging its Boundaries so as to render it at once an example and fit instrument for introducing the same absolute rule into these Colonies.', difficulty_order: 12 },
  { path: 'founders', title: 'Of the People', author: 'Abraham Lincoln', content: 'But, in a larger sense, we can not dedicate—we can not consecrate—we can not hallow—this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced.', difficulty_order: 13 },
  { path: 'founders', title: 'The Pursuit of Knowledge', author: 'Thomas Jefferson', content: 'If a nation expects to be ignorant and free, in a state of civilization, it expects what never was and never will be. The functionaries of every government have propensities to command at will the liberty and property of their constituents. There is no safe deposit for these but with the people themselves; nor can they be safe with them without information. Where the press is free and every man able to read, all is safe.', difficulty_order: 14 },
  { path: 'founders', title: 'Checks and Balances', author: 'James Madison', content: 'The accumulation of all powers, legislative, executive, and judiciary, in the same hands, whether of one, a few, or many, and whether hereditary, self-appointed, or elective, may justly be pronounced the very definition of tyranny. Were the executive magistrate, or the judges, not independent of the legislature in this particular, their independence in every other would be merely nominal. But the great security against a gradual concentration of the several powers in the same department, consists in giving to those who administer each department the necessary constitutional means and personal motives to resist encroachments of the others.', difficulty_order: 15 },
  { path: 'founders', title: 'A House Divided', author: 'Abraham Lincoln', content: 'A house divided against itself cannot stand. I believe this government cannot endure, permanently half slave and half free. I do not expect the Union to be dissolved—I do not expect the house to fall—but I do expect it will cease to be divided. It will become all one thing or all the other. Either the opponents of slavery, will arrest the further spread of it, and place it where the public mind shall rest in the belief that it is in the course of ultimate extinction; or its advocates will push it forward, till it shall become alike lawful in all the States, old as well as new—North as well as South.', difficulty_order: 16 },
  { path: 'founders', title: 'Washington\'s Warning', author: 'George Washington', content: 'However political parties may now and then answer popular ends, they are likely in the course of time and things, to become potent engines, by which cunning, ambitious, and unprincipled men will be enabled to subvert the power of the people and to usurp for themselves the reins of government, destroying afterwards the very engines which have lifted them to unjust dominion. Let me now take a more comprehensive view, and warn you in the most solemn manner against the baneful effects of the spirit of party generally. This spirit, unfortunately, is inseparable from our nature, having its root in the strongest passions of the human mind. It exists under different shapes in all governments, more or less stifled, controlled, or repressed; but, in those of the popular form, it is seen in its greatest rankness, and is truly their worst enemy.', difficulty_order: 17 },
  { path: 'founders', title: 'Franklin on Virtue', author: 'Benjamin Franklin', content: 'Only a virtuous people are capable of freedom. As nations become more corrupt and vicious, they have more need of masters. When the people find that they can vote themselves money, that will herald the end of the republic. Sell not virtue to purchase wealth, nor Liberty to purchase power. The Constitution only gives people the right to pursue happiness. You have to catch it yourself. Money has never yet made anyone rich. He that is of the opinion money will do everything may well be suspected of doing everything for money. A penny saved is a penny earned. Remember that time is money. Well done is better than well said.', difficulty_order: 18 },
  { path: 'founders', title: 'Malice Toward None', author: 'Abraham Lincoln', content: 'With malice toward none, with charity for all, with firmness in the right as God gives us to see the right, let us strive on to finish the work we are in, to bind up the nation\'s wounds, to care for him who shall have borne the battle and for his widow and his orphan, to do all which may achieve and cherish a just and lasting peace among ourselves and with all nations. Fondly do we hope, fervently do we pray, that this mighty scourge of war may speedily pass away. Yet, if God wills that it continue until all the wealth piled by the bondsman\'s two hundred and fifty years of unrequited toil shall be sunk, and until every drop of blood drawn with the lash shall be paid by another drawn with the sword, as was said three thousand years ago, so still it must be said "the judgments of the Lord are true and righteous altogether."', difficulty_order: 19 },
  { path: 'founders', title: 'The Declaration\'s Resolve', author: 'Declaration of Independence', content: 'We, therefore, the Representatives of the united States of America, in General Congress, Assembled, appealing to the Supreme Judge of the world for the rectitude of our intentions, do, in the Name, and by Authority of the good People of these Colonies, solemnly publish and declare, That these United Colonies are, and of Right ought to be Free and Independent States; that they are Absolved from all Allegiance to the British Crown, and that all political connection between them and the State of Great Britain, is and ought to be totally dissolved; and that as Free and Independent States, they have full Power to levy War, conclude Peace, contract Alliances, establish Commerce, and to do all other Acts and Things which Independent States may of right do. And for the support of this Declaration, with a firm reliance on the protection of divine Providence, we mutually pledge to each other our Lives, our Fortunes and our sacred Honor.', difficulty_order: 20 }
];

async function populateDatabase() {
  console.log('🚀 Starting database population...');
  console.log('Note: This is just the first part (Stoics + Founders). Full content will be added next.');

  try {
    // First, check if there are any existing passages
    const { count, error: countError } = await supabase
      .from('passages')
      .select('*', { count: 'exact', head: true });

    if (countError) {
      console.error('❌ Error checking existing data:', countError);
      return;
    }

    console.log(`📊 Found ${count} existing passages`);

    if (count > 0) {
      console.log('⚠️  Database already has data. Clearing first...');
      const { error: deleteError } = await supabase
        .from('passages')
        .delete()
        .neq('id', '00000000-0000-0000-0000-000000000000'); // Delete all

      if (deleteError) {
        console.error('❌ Error clearing data:', deleteError);
        return;
      }
      console.log('✅ Cleared existing data');
    }

    // Insert all passages
    console.log(`📝 Inserting ${passages.length} passages...`);

    const { data, error } = await supabase
      .from('passages')
      .insert(passages)
      .select();

    if (error) {
      console.error('❌ Error inserting passages:', error);
      return;
    }

    console.log(`✅ Successfully inserted ${data.length} passages!`);
    console.log('📚 stoics: 25 passages');
    console.log('📚 founders: 20 passages');
    console.log('\n🔄 Next: Add all the comprehensive content for other paths');

  } catch (err) {
    console.error('❌ Unexpected error:', err);
  }
}

populateDatabase();